Кустова Анастасия. Задача 2. Итеративные методы (Якоби)
allnes/pp_2020_autumn_engineer pull request #104
Opened 2020-11-09 13:21 UTC by KustovaAI

2020-11-13 22:10 UTC, allnes requested changes

2020-11-13 22:10 UTC, allnes commented on modules/task_2/kustova_a_jacoby/start.sh
> +cd ../../../build
пожалуйста добавляйте файлы относящиеся только к решению задачи

2020-11-13 22:10 UTC, allnes commented on modules/task_1/kustova_a_max_vector/main.cpp
> +    const int len = 1001;
пожалуйста добавляйте файлы относящиеся только к текущей задаче

2020-11-14 17:31 UTC, KustovaAI commented on modules/task_1/kustova_a_max_vector/main.cpp
> +    const int len = 1001;
Исправила.

2020-11-14 17:32 UTC, KustovaAI commented on modules/task_2/kustova_a_jacoby/start.sh
> +cd ../../../build
Исправила.

2020-11-20 22:30 UTC, allnes approved these changes

2020-11-20 22:30 UTC, merged