Горбунова Валерия.Задача 2.Обобщенная передача от одного всем (scatter)
allnes/pp_2020_autumn_engineer pull request #120
Opened 2020-11-19 16:49 UTC by GorbunovaVI

2020-11-19 18:31 UTC, GorbunovaVI commented
Извините что так много коммитов, не могу понять почему линукс и мак не устраивает функция memcpy.Закройте пожалуйста этот реквест,чтобы я смогла у себя настроить проверку,и потом отправить сразу правильный вариант.

2020-11-20 22:39 UTC, allnes requested changes

2020-11-20 22:39 UTC, allnes commented on scripts/run.bat
> -        "C:\Program Files\Microsoft MPI\Bin\mpiexec.exe" -np 4 %%~fa || exit /b 1
убрать лишние изменения в реквесте

2020-11-20 22:39 UTC, allnes requested changes

2020-11-20 22:39 UTC, allnes commented on modules/task_1/gorbunova_v_lexicograph/main.cpp
> +TEST(lexicograph_orderd, two_generating_strings2) {
изменения должны касаться только текущей задачи

2020-11-21 09:40 UTC, closed without merging