Алексей Некравцев. Задача 1. Вычислить сумму элементов матрицы
allnes/pp_2020_autumn_engineer pull request #35
Opened 2020-10-23 08:03 UTC by Alexey42

2020-10-23 21:56 UTC, allnes requested changes

2020-10-23 21:56 UTC, allnes commented on modules/task_1/nekravtsev_a_matrix_sum/matrix_sum.cpp
> +  std::vector<std::vector<int>> result(rows);
матрица должна представляться в виде одного вектора (линейно)

2020-10-24 09:23 UTC, Alexey42 commented on modules/task_1/nekravtsev_a_matrix_sum/matrix_sum.cpp
> +  std::vector<std::vector<int>> result(rows);
исправил. почему она должна так представляться?

2020-10-29 20:23 UTC, allnes commented on modules/task_1/nekravtsev_a_matrix_sum/matrix_sum.cpp
> +  std::vector<std::vector<int>> result(rows);
> исправил. почему она должна так представляться?

в основном для скорости доступа к данным

2020-10-29 20:23 UTC, allnes approved these changes

2020-10-29 20:23 UTC, merged