Кочанков Илья. Задача 1. Сумма значений по столбцам матрицы.
allnes/pp_2020_autumn_engineer pull request #41
Opened 2020-10-26 11:06 UTC by KochankovID

Задача заключается в разделении матрицы на равные (почти) части, параллельном подсчете суммы элементов для каждого столбца в части и получение результирующего вектора значений.

2020-10-30 10:30 UTC, allnes requested changes

2020-10-30 10:30 UTC, allnes commented on modules/task_1/kochankov_i_matrix_columns_sum/CMakeLists.txt
> +    add_library(${PACK_LIB} STATIC ${header_files} ${source_files} Matrix.cpp Matrix.h)
система автоматически видит ваши файлы, не надо изменять это.

2020-10-30 10:30 UTC, allnes commented on modules/task_1/kochankov_i_matrix_columns_sum/Matrix.cpp
> +Matrix::Matrix(const Matrix &copy) : _rows(copy._rows), _columns(copy._columns) {
слишком массивный класс, достаточно `std::vector<double>` и формулы для доступа к элементу

2020-10-30 10:56 UTC, KochankovID commented on modules/task_1/kochankov_i_matrix_columns_sum/Matrix.cpp
> +Matrix::Matrix(const Matrix &copy) : _rows(copy._rows), _columns(copy._columns) {
Массивный, но рабочий же. Можно так оставить? мне везде придется менять это. Вектор с формулой доступа к элементу это либо вектор + доп функция - что не удобно. Либо наследование от вектора, что тоже займет не меньший объем кода.

2020-10-30 23:40 UTC, allnes requested changes

2020-10-30 23:40 UTC, allnes commented on modules/task_1/kochankov_i_matrix_columns_sum/CMakeLists.txt
> +    add_executable( ${ProjectId} ${source_files} main.cpp)
система автоматически видит и это тоже, вообще не надо менять CMakeLists

2020-10-30 23:40 UTC, allnes commented on modules/task_1/kochankov_i_matrix_columns_sum/Matrix.cpp
> +Matrix::Matrix(const Matrix &copy) : _rows(copy._rows), _columns(copy._columns) {
можно так оставить, но на будущее - это сильное усложнение, под формулой я имел ввиду `vec[i * len_row + j] ` - обычный доступ

2020-10-31 11:22 UTC, allnes approved these changes

2020-10-31 11:22 UTC, merged